---

## NTP install and setup
- name: Install ntp
  apt:
    pkg: ntp
    state: present

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service:
    name: ntp
    state: started
    enabled: yes
