---
# defaults file for mongodb on Ubuntu/Debian
mongodb_bind_address: 127.0.0.1
mongodb_port: 27017

# Debian vars
mongodb_service_name: mongod
mongodb_packages:
  - mongodb-org # =4.0.1
  - mongodb-org-server # =4.0.1
  - mongodb-org-mongos # =4.0.1
  - mongodb-org-shell # =4.0.1
  - mongodb-org-tools # =4.0.1
  - python-pymongo

# Just in case we need to fix the installation to a specific version
mongodb_pinned_packages: []
  # - mongodb-org
  # - mongodb-org-server
  # - mongodb-org-shell
  # - mongodb-org-mongos
  # - mongodb-org-tools

mongodb_dbpath: /var/lib/mongodb
mongodb_logpath: /var/log/mongodb/mongodb.log

# Must be one of enabled/disabled
mongodb_authorization: disabled
