---
# defaults file for apache2

apache2_modules_disabled:
  - autoindex
  - authn_anon
  - cgi
  - dav
  - negotiation
  - status
  - userdir

apache2_modules_enabled:
  - alias
  - env
  - setenvif # required by SSL mod
  - auth_digest
  - authz_host
  - deflate
  - dir
  - headers
  - reqtimeout
  - rewrite
  - ssl
  - unique_id

apache2_www_folder: /var/www
apache2_doc_root_owner: root
apache2_doc_root_group: root
