# -*- mode: ruby -*-
# vi: set ft=ruby :

# A name for your project
PROJECT = 'docker-dev'

## Provision settings
## These settings have effect on provision
MEMORY = 512

VAGRANTFILE_API_VERSION = 2
Vagrant.require_version ">= 1.8.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Cache software packages
  if Vagrant.has_plugin?("vagrant-cachier")
     config.cache.enable :apt
     config.cache.enable :apt_lists
     config.cache.enable :composer
  end

  # Use custom key path, leave commented until after first provision
  # config.ssh.private_key_path = "#{ENV['HOME']}/.ssh/id_rsa"

  # VM definition
  config.vm.define PROJECT do |trusty|

    # Box details
    # Note: consider hosting you own boxes (ie http://virtualboxes.loc/boxes/jessie64.box)
    trusty.vm.box      = 'ubuntu/trusty64'
    trusty.vm.box_url  = 'https://atlas.hashicorp.com/ubuntu/boxes/trusty64'
    trusty.vm.hostname = PROJECT

    # Networking setup
    trusty.vm.network "private_network", type: "dhcp"

    # Share Docker port
    trusty.vm.network :forwarded_port, guest: 2375, host: 2375
    trusty.vm.network :forwarded_port, guest: 2376, host: 2376

    # Basic port forwarding (HTTP, HTTPS)
    trusty.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true
    trusty.vm.network :forwarded_port, guest: 443, host: 8443, auto_correct: true

    # Standard Node/Ruby ports
    trusty.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true
    trusty.vm.network :forwarded_port, guest: 5000, host: 5000, auto_correct: true

    # MySQL/MongoDB ports
    trusty.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true
    trusty.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true

    # Share Home directory with the same path on VM (it may require your password on startup)
    # You could enable NFS sharing protocol, but it has some problems with Ruby bundle installs
    trusty.vm.synced_folder ENV['HOME'], ENV['HOME'], id: "home" #, :nfs => true, :mount_options => ['nolock,vers=3,udp']

    # VM Provider specific settings for VirtualBox
    trusty.vm.provider "virtualbox" do |vb|

      # Share VPN connections
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

      vb.name = PROJECT

      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true

      # Customize the amount of memory on the VM:
      vb.memory = "#{MEMORY}"
    end

    # Add custom key
    trusty.vm.provision :file, :source => "#{ENV['HOME']}/.ssh/id_rsa.pub", :destination => "/tmp/vagrantfile-pubkey"
    trusty.vm.provision :shell, :privileged => false, :inline => <<-SHELL
      cat /tmp/vagrantfile-pubkey >> $HOME/.ssh/authorized_keys
      SHELL

    # Enable provisioning with a shell script.
    config.vm.provision "shell", inline: <<-SHELL

      export LC_ALL="en_US.UTF-8"
      export DEBIAN_FRONTEND=noninteractive

      # fix invalid locale settings
      echo "LANG=\"en_US.UTF-8\"
      LC_ALL=\"en_US.UTF-8\"" > /etc/default/locale

      # update repos
      apt-get update
      apt-get upgrade -y

      # make sure wget is installed and install Docker from site
      apt-get -y install wget
      wget -qO- https://get.docker.com/ | sh

      # add vagrant user to docker group
      gpasswd -a vagrant docker

      # edit DNSs and allow connections from external (dev only, please!)
      echo 'DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -H 0.0.0.0:2375"' >> /etc/default/docker

      # restart service
      service docker restart

      # cleanup unused packages
      apt-get autoremove -y

      # test Docker installation
      docker run hello-world

    SHELL
  end

end
