# -*- mode: ruby -*-
# vi: set ft=ruby :

# A name for your project
PROJECT = 'mongodb-box'

## Provision settings
## These settings have effect on provision

## End Provision settings

VAGRANTFILE_API_VERSION = 2
Vagrant.require_version ">= 1.8.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Cache software packages
  if Vagrant.has_plugin?("vagrant-cachier")
     config.cache.enable :apt
     config.cache.enable :apt_lists
     config.cache.enable :composer
  end

  # Use custom key path, leave commented until after first provision
  # config.ssh.private_key_path = "#{ENV['HOME']}/.ssh/id_rsa"

  # VM definition
  config.vm.define PROJECT do |jessie|

    # Box details
    # Note: consider hosting you own boxes (ie http://virtualboxes.loc/boxes/jessie64.box)
    jessie.vm.box      = 'debian/jessie64'
    jessie.vm.box_url  = 'https://atlas.hashicorp.com/debian/boxes/jessie64'
    jessie.vm.hostname = PROJECT

    # Networking setup
    jessie.vm.network "private_network", type: "dhcp"

    # MongoDB port forwarding
    jessie.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true

    # Disable default Vagrant share, turn it on only when needed (ie copy large files)
    jessie.vm.synced_folder ".", "/vagrant", disabled: true

    # VM Provider specific settings for VirtualBox
    jessie.vm.provider "virtualbox" do |vb|

      # Share VPN connections
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

      vb.name = PROJECT

      # Customize the amount of memory on the VM:
      vb.memory = "512"
    end

    # Add custom key
    jessie.vm.provision :file, :source => "#{ENV['HOME']}/.ssh/id_rsa.pub", :destination => "/tmp/vagrantfile-pubkey"
    jessie.vm.provision :shell, :privileged => false, :inline => <<-SHELL
      cat /tmp/vagrantfile-pubkey >> $HOME/.ssh/authorized_keys
      SHELL

    # Provisioning with Ansible
    jessie.vm.provision "ansible" do |ansible|
      # Vagrant auto generates the inventory file, uncomment below to use yours
      # ansible.inventory_path = "hosts"

      # Custom config
      # ENV['ANSIBLE_CONFIG'] = "/path/to/custom/ansible.cfg"
      # Example:
      # ENV['ANSIBLE_CONFIG'] = "#{ENV['HOME']}/Dev/Ansible/ansible.cfg"

      # Add the box to mongodb group and use custom group vars
      ansible.groups = {
        "mongodb" => PROJECT,
        "mongodb:vars" => {
          "variable1" => 9,
          "variable2" => "example"
        }
      }

      # Custom host vars
      ansible.host_vars = {
        PROJECT => {

          # Local development specific settings
          "mongodb_bind_address" => "0.0.0.0" # Expose MongoDB to the world
        }
      }

      # Use local playbook that has access to shared roles, with custom vars above
      ansible.playbook = "ansible/mongodb.yml"
    end

  end
end
