# -*- mode: ruby -*-
# vi: set ft=ruby :

# A name for your project
PROJECT = 'node-box'

## Provision settings
## These settings have effect on provision

## End Provision settings

VAGRANTFILE_API_VERSION = 2
Vagrant.require_version ">= 2.2.0"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Cache software packages
  if Vagrant.has_plugin?("vagrant-cachier")
     config.cache.enable :apt
     config.cache.enable :apt_lists
     config.cache.enable :composer
  end

  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  end

  # Use custom key path, leave commented until after first provision
  # config.ssh.private_key_path = "#{ENV['HOME']}/.ssh/id_rsa"

  # VM definition
  config.vm.define PROJECT do |guest|

    # Box details
    # Note: consider hosting you own boxes (ie http://virtualboxes.loc/boxes/stretch64.box)
    guest.vm.box      = 'debian/stretch64'
    guest.vm.box_url  = 'https://atlas.hashicorp.com/debian/boxes/stretch64'
    guest.vm.hostname = PROJECT

    # Networking setup
    guest.vm.network "private_network", type: "dhcp"

    # Port forwarding (MySQL, MongoDB, HTTP, HTTPS and common Node.js)
    guest.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true
    guest.vm.network :forwarded_port, guest: 8443, host: 8443, auto_correct: true
    guest.vm.network :forwarded_port, guest: 3306, host: 3306, auto_correct: true
    guest.vm.network :forwarded_port, guest: 27017, host: 27017, auto_correct: true
    guest.vm.network :forwarded_port, guest: 3000, host: 3000, auto_correct: true

    # Share the source code of you project
    guest.vm.synced_folder "./src", "/app",
      disabled: false,
      owner: "vagrant",
      group: "vagrant"
      # mount_options: ["dmode=775,fmode=774,umask=000"]


    # You may want share MySQL/MongoDB databases between the host and the guest...
    guest.vm.synced_folder "/Users/Shared/mysql", "/var/lib/mysql", disabled: true

    # VM Provider specific settings for VirtualBox
    guest.vm.provider "virtualbox" do |vb|

      # Share VPN connections
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

      vb.name = PROJECT

      # Customize the amount of memory on the VM:
      vb.memory = "512"
    end

    # Add custom key
    guest.vm.provision :file, :source => "#{ENV['HOME']}/.ssh/id_rsa.pub", :destination => "/tmp/vagrantfile-pubkey"
    guest.vm.provision :shell, :privileged => false, :inline => <<-SHELL
      cat /tmp/vagrantfile-pubkey >> $HOME/.ssh/authorized_keys
      SHELL

    # Provisioning with Ansible
    guest.vm.provision "ansible" do |ansible|
      # Vagrant auto generates the inventory file, uncomment below to use yours
      # ansible.inventory_path = "hosts"

      # Custom config
      # ENV['ANSIBLE_CONFIG'] = "/path/to/custom/ansible.cfg"
      # Example:
      # ENV['ANSIBLE_CONFIG'] = "#{ENV['HOME']}/Dev/Ansible/ansible.cfg"

      # Add the box to node group and use custom group vars
      ansible.groups = {
        "node" => PROJECT,
        "node:vars" => {
          "variable1" => 9,
          "variable2" => "example"
        }
      }

      # Custom host vars
      ansible.host_vars = {
        PROJECT => {
        }
      }

      # ansible.verbose = "vvvv"

      # Use local playbook that has access to shared roles, with custom vars above
      ansible.playbook = "ansible/node.yml"
    end

  end
end
