---

- name: Debian | install packages
  apt:
    pkg: "{{ php_apache2_packages }}"
    state: present
  register: php_apache2_install

- name: ensure PHP is enabled on Apache
  apache2_module:
    name: php7
    state: present
  notify:
    - restart apache2
  tags:
    - harden
